### PR TITLE
Add defaults to global variables

### PR DESCRIPTION
**Pull request by AlexWaygood**
This works, but there's currently a lot of duplication in code. Ideally there'd be more code shared, but I figured I'd show you where I'm at with it for now anyway.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'll take a look at the code later, but I was wondering if you were planning on making any typeshed PRs to apply the improvements you've been making? It might be better to get a bunch of these changes in first before moving on to potentially riskier areas like globals.

**Comment by AlexWaygood** [comment]
> It might be better to get a bunch of these changes in first before moving on to potentially riskier areas like globals.

We can hold off for now, for sure; there's no rush. I'm nervous about adding more defaults to typeshed until we have a release of flake8-pyi with https://github.com/PyCQA/flake8-pyi/pull/339 in it (and preferably also we'd use a version of stubtest that verifies the defaults).

**Comment by AlexWaygood** [comment]
> > It might be better to get a bunch of these changes in first before moving on to potentially riskier areas like globals.
> 
> We can hold off for now, for sure; there's no rush. I'm nervous about adding more defaults to typeshed until we have a release of flake8-pyi with [PyCQA/flake8-pyi#339](https://github.com/PyCQA/flake8-pyi/pull/339) in it (and preferably also we'd use a version of stubtest that verifies the defaults).

Actually I meant "until we have a release of flake8-pyi with https://github.com/PyCQA/flake8-pyi/commit/29ba4e3ba45f7b257a0242f0992c3b71894047cd in it", but I was holding off a new release until PyCQA/flake8-pyi#339 had been reviewed :)

**Comment by JelleZijlstra** [comment]
> but I was holding off a new release until [PyCQA/flake8-pyi#339](https://github.com/PyCQA/flake8-pyi/pull/339) had been reviewed :)

Hint hint :) I'll take a look tonight.

**Comment by AlexWaygood** [comment]
Closing for now, there's lots of conflicts and I don't think this should be a priority

**Pull request closed without merging**
